ALTER TABLE public.users
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.regions
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.gardens
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.plants
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.user_plants
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.user_plant_tags
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.watering_logs
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.observation_logs
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.weather_cache
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.plant_master_requests
ENABLE ROW LEVEL SECURITY;
