ALTER TABLE users
ENABLE ROW LEVEL SECURITY;

ALTER TABLE regions
ENABLE ROW LEVEL SECURITY;

ALTER TABLE gardens
ENABLE ROW LEVEL SECURITY;

ALTER TABLE plants
ENABLE ROW LEVEL SECURITY;

ALTER TABLE user_plants
ENABLE ROW LEVEL SECURITY;

ALTER TABLE user_plant_tags
ENABLE ROW LEVEL SECURITY;

ALTER TABLE watering_logs
ENABLE ROW LEVEL SECURITY;

ALTER TABLE observation_logs
ENABLE ROW LEVEL SECURITY;

ALTER TABLE weather_cache
ENABLE ROW LEVEL SECURITY;

ALTER TABLE plant_master_requests
ENABLE ROW LEVEL SECURITY;
